name: Keyzilla CI

on:
  push:
    branches: [main]
    paths:
      - "@keyzilla/**"
  pull_request:
    branches: [main]
    paths:
      - "@keyzilla/**"
  workflow_dispatch:

permissions:
  contents: read
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: packages/keyzilla

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - uses: actions/checkout@v4
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: "packages/keyzilla/package.json"
      - run: npm audit signatures
      - name: Install dependencies
        run: npm install
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Publish to npm
        run: npm run semantic-release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
