name: Test and release

on:
  push:
    branches: [main]
    paths:
      - "packages/keyzilla/**"
  pull_request:
    branches: [main]
    paths:
      - "packages/keyzilla/**"
  workflow_dispatch:

permissions:
  contents: write
  issues: write
  pull-requests: write

jobs:
  build:
    runs-on: blacksmith-4vcpu-ubuntu-2204

    defaults:
      run:
        working-directory: packages/keyzilla

    strategy:
      matrix:
        node-version: [lts/*]

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Use Node.js ${{ matrix.node-version }}
        uses: useblacksmith/setup-node@v5
        with:
          node-version: ${{ matrix.node-version }}
          cache: "npm"
          cache-dependency-path: packages/keyzilla/package.json
      - name: Install dependencies
        run: npm install
      - name: npm lint
        run: npm run lint
      - name: Run build
        run: npm run build
      - name: Run tests
        run: npm test
      - name: Publish to npm
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
        run: npx semantic-release
